import type { Metadata, Viewport } from 'next'

import { Providers } from '@/app/[locale]/providers'
import { Navbar } from '@/app/components'
import { cn } from '@enes-sh/utils'

import '@/app/tailwind.css'

type LayoutProps = {
  children: React.ReactNode
  params: { locale: string }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'black' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}

export default function Layout({ children, params: { locale } }: LayoutProps) {
  return (
    <html lang={locale}>
      <body className={cn('min-h-screen font-sans antialiased')}>
        <Providers>
          {children}
          <Navbar />
        </Providers>
      </body>
    </html>
  )
}
