import type { Metadata, Viewport } from 'next'

import { Navbar } from '@app/components'
import { Providers } from '@app/providers'
import { cn } from '@app/utils'

import '@app/tailwind.css'

type LayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'black' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen font-sans antialiased')}>
        <Providers>
          {children}
          <Navbar />
        </Providers>
      </body>
    </html>
  )
}
