import type { Metadata, Viewport } from 'next'

import 'app/tailwind.css'

type LayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'white' }
  ]
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
