import type { Metadata } from 'next';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';

import { routing } from '../i18n/routing';
import { Locale } from '../i18n/types';

import { PropsWithChildren } from 'react';
import { ApolloWrapper } from '../features/graphql/apollo-wrapper';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type LocaleLayoutProps = {
  params: {
    locale: string;
  };
};

export default async function LocaleLayout({
  children,
  params,
}: PropsWithChildren<LocaleLayoutProps>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <ApolloWrapper>
          <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
