import type { Metadata } from 'next'

import { CenteredLayout } from '@/app/components'

export type LayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: LayoutProps) {
  return <CenteredLayout>{children}</CenteredLayout>
}
