import type { Metadata, Viewport } from 'next'

import { CenteredLayout } from '@/app/components'

import '@/app/tailwind.css'

type LayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'black' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}

export default function Layout({ children }: LayoutProps) {
  return <CenteredLayout>{children}</CenteredLayout>
}
