import { NextAuthProvider } from '@/app/providers'
import { TooltipProvider } from '@enes-sh/ui'
import type { Metadata, Viewport } from 'next'

import '@/app/tailwind.css'

type LayoutProps = {
  children: React.ReactNode
  params: { locale: string }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'black' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}

export default function Layout({ children, params: { locale } }: LayoutProps) {
  return (
    <html lang={locale}>
      <body>
        <NextAuthProvider>
          <TooltipProvider delayDuration={200}>{children}</TooltipProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
